modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/pHren9yxzW"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ram-compat"
authors = "${mod_authors}"
description = '''Compat addon between Relics and Alex's mobs'''

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "curios"
mandatory = true
versionRange = "[5.2.0+1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "octolib"
mandatory = true
versionRange = "[0.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "relics"
mandatory = true
versionRange = "[0.5.2,)"
ordering = "NONE"
side = "BOTH"